Update codeCov.yml

diff --git a/.github/workflows/codeCov.yml b/.github/workflows/codeCov.yml
--- a/.github/workflows/codeCov.yml
+++ b/.github/workflows/codeCov.yml
@@ -25,25 +25,18 @@ jobs:
       run: go test -v ./...
 
 
-    - name: CodeCov Test
+    - name: Quality Gate - Test coverage shall be above threshold
+      env:
+          TESTCOVERAGE_THRESHOLD: 0
       run: |
-        CVPKG=$(go list ./... | grep -v mocks | tr '\n' ',')
-        go test -coverpkg=${CVPKG} -coverprofile=coverage.out -covermode=count  ./...
-    - name: Setup gcloud cli
-      uses: google-github-actions/setup-gcloud@v0
-      with:
-        version: '290.0.1'
-        project_id: ${{ secrets.PROJECT_ID }}
-        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
-        export_default_credentials: true
-    - name: Publish cod cov badge
-      run: |
-        set -x
-        total=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-        if (( $(echo "$total <= 50" | bc -l) )) ; then
-          COLOR=red
-        elif (( $(echo "$total > 80" | bc -l) )); then
-          COLOR=green
-        else
-          COLOR=orange
-        fi
+            echo "Quality Gate: checking test coverage is above threshold ..."
+            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+            fi
